name: 04 - Using Actions
run-name: 04 - Using Actions ${{ github.event_name }}
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x.x'
      - name: install tree
        run: sudo apt-get install -y tree
      - name: List files
        run: tree -L 4
      - name: install dependencies
        run: npm ci
        working-directory: ./04-using-actions/react-app
      - name: Run tests
        run: npm run test -- --watchAll=false
        working-directory: ./04-using-actions/react-app
      - name: Build app
        run: npm run build
        working-directory: ./04-using-actions/react-app
      - name: run app
        run: npm run start
        working-directory: ./04-using-actions/react-app