name: 05 - 2 - Filters Activity Types
run-name: 05 - 2 - Filters Activity Types
on:
  workflow_dispatch:
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "Running whenever a PR is closed"
