name: 06 - Contexts
run-name: 06 - Contexts
description: |
  This example demonstrates how to use contexts in a YAML file.
  Contexts allow you to define reusable configurations that can be applied to multiple resources.
on: 
  push: 
    branches:
      - main
  workflow_dispatch:
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "branch: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Repository: ${{ github.repository }}"
          echo "Job: ${{ github.job }}"
          echo "Run Attempt: ${{ github.run_attempt }}"
      - name: Retrieve Variable
        run: |
          echo "Variable from context: ${{ vars.MY_VAR }}"
          echo "Variable from context: ${{ vars.MY_PASS }}"
