name: 06 - Contexts
run-name: 06 - Contexts
description: |
  This example demonstrates how to use contexts in a YAML file.
  Contexts allow you to define reusable configurations that can be applied to multiple resources.
on: 
  push: 
    branches:
      - main
  workflow_dispatch:
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job: ${{ github.job }}"
          echo "Run Attempt: ${{ github.run_attempt }}"
          echo "Event Payload: ${{ toJson(github.event) }}"
          echo "Workflow Context: ${{ toJson(github.workflow_context) }}"
          echo "Repository Context: ${{ toJson(github.repository_context) }}"
          echo "Actor Context: ${{ toJson(github.actor_context) }}"
          echo "Ref Context: ${{ toJson(github.ref_context) }}"
          echo "SHA Context: ${{ toJson(github.sha_context) }}"
          echo "Run ID Context: ${{ toJson(github.run_id_context) }}"
          echo "Run Number Context: ${{ toJson(github.run_number_context) }}"
          echo "Job Context: ${{ toJson(github.job_context) }}"
          echo "Run Attempt Context: ${{ toJson(github.run_attempt_context) }}"
          echo "Workflow Dispatch Inputs: ${{ toJson(github.workflow_dispatch_inputs) }}"
          echo "Workflow Permissions: ${{ toJson(github.workflow_permissions) }}"
          echo "Workflow Environment: ${{ toJson(github.workflow_environment) }}"
          echo "Workflow Secrets: ${{ toJson(github.workflow_secrets) }}"
          echo "Workflow Outputs: ${{ toJson(github.workflow_outputs) }}"
          echo "Workflow Status: ${{ github.workflow_status }}"
          echo "Workflow Conclusion: ${{ github.workflow_conclusion }}"
          echo "Workflow Created At: ${{ github.workflow_created_at }}"
          echo "Workflow Updated At: ${{ github.workflow_updated_at }}"
          echo "Workflow Run URL: ${{ github.workflow_run_url }}"
          echo "Workflow Run Number: ${{ github.workflow_run_number }}"
          echo "Workflow Run Attempt: ${{ github.workflow_run_attempt }}"
          echo "Workflow Run ID: ${{ github.workflow_run_id }}"
          echo "Workflow Run Attempt Context: ${{ toJson(github.workflow_run_attempt_context) }}"
          echo "Workflow Run ID Context: ${{ toJson(github.workflow_run_id_context) }}"
          echo "Workflow Run Number Context: ${{ toJson(github.workflow_run_number_context) }}"
          echo "Workflow Run URL Context: ${{ toJson(github.workflow_run_url_context) }}"
          echo "Workflow Run Created At: ${{ github.workflow_run_created_at }}"
          echo "Workflow Run Updated At: ${{ github.workflow_run_updated_at }}"
          echo "Workflow Run Status: ${{ github.workflow_run_status }}"
          echo "Workflow Run Conclusion: ${{ github.workflow_run_conclusion }}"
          echo "Workflow Run Environment: ${{ toJson(github.workflow_run_environment) }}"
          echo "Workflow Run Permissions: ${{ toJson(github.workflow_run_permissions) }}"
          echo "Workflow Run Secrets: ${{ toJson(github.workflow_run_secrets) }}"
          echo "Workflow Run Outputs: ${{ toJson(github.workflow_run_outputs) }}"
          echo "Workflow Run Inputs: ${{ toJson(github.workflow_run_inputs) }}"
          echo "Workflow Run Artifacts: ${{ toJson(github.workflow_run_artifacts) }}"
          echo "Workflow Run Logs: ${{ toJson(github.workflow_run_logs) }}"
          echo "Workflow Run Annotations: ${{ toJson(github.workflow_run_annotations) }}"
          echo "Workflow Run Check Suites: ${{ toJson(github.workflow_run_check_suites) }}"
          echo "Workflow Run Check Runs: ${{ toJson(github.workflow_run_check_runs) }}"
          echo "Workflow Run Commits: ${{ toJson(github.workflow_run_commits) }}"
          echo "Workflow Run Pull Requests: ${{ toJson(github.workflow_run_pull_requests) }}"
          echo "Workflow Run Issues: ${{ toJson(github.workflow_run_issues) }}"
          echo "Workflow Run Releases: ${{ toJson(github.workflow_run_releases) }}"