name: 07 - Using Expressions
run-name: 07 - Using Expressions

on: 
  workflow_dispatch:
    inputs:
      Debug:
        default: false
        type: boolean
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.Debug == true }}
        name: Debug Print start-up data
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"