name: 07 - Using Expressions
run-name:  '07 - Using Expressions - ${{ github.ref_name }} - Debug Mode: ${{ inputs.Debug }}'

on: 
  workflow_dispatch:
    inputs:
      Debug:
        default: false
        type: boolean
      Branch:
        default: "main"
        type: string
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.Debug == true }}
        name: '[debug] Print start-up data'
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - if: ${{ inputs.Debug == true && github.ref_name == 'main' }}
        name: '[debug] Print when triggered from main'
        run: | 
          echo "I was triggered from ${{ github.ref_name }} branch" 
      - name: Greating
        run: |
          echo "Hello, world!"
          echo "This is a workflow that uses expressions to control execution flow."