name: 09 - Using Functions
run-name: 09 - Using Functions

on:
  workflow_dispatch:
  pull_request:
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: |
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
      - name: Print PR labels
        run: |
          echo " Pull Request Labels: ${{ toJSON(github.event) }}"
      - name: initial step
        run: |
          sleep 10
          echo "This step will not fail."
      - if: ${{ success() }}
        name: I will be skipped
        run: |
          echo "This step will be skipped if the previous step failed."
      - if: ${{ failure() }}
        name: I will run if the previous step failed
        run: |
          echo "This step will run if the previous step failed."
      - if: ${{ cancelled() }}
        name: I will run if the workflow was cancelled
        run: |
          echo "This step will run if the workflow was cancelled."