name: 14 - Working with Artifacts
run-name: 14 - Working with Artifacts
on:
  workflow_dispatch:
    inputs:
      artifact-name:
        description: 'Name of the artifact to create'
        required: true
        default: 'example-artifact'
      cache-enabled:
        description: 'Enable caching for the artifact'
        required: false
        type: boolean
        default: 'true'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      steps.cache.cache-hit: ${{ steps.cache.outputs.cache-hit }}
    defaults:
      run:
        working-directory: 14-artifacts/ntfy-desktop
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Caching step
        if: inputs.cache-enabled
        id: cache
        uses: actions/cache@v4
        with:
          path: 14-artifacts/ntfy-desktop/**/node_modules
          key: ${{ runner.os }}-${{ hashFiles('14-artifacts/**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci 
          cd src && npm ci 
      - name: Unit test
        run: |
          npm run test || echo "Tests failed, but continuing to build artifact."
      - name: Build Project
        run: bash ./build.sh
      - name: Create Artifact
        id: create-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}-${{ github.run_id }}
          path: 14-artifacts/ntfy-desktop/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}-${{ github.run_id }}
          path: app/
      - name: List Artifact Contents
        run: |
          echo ${{ needs.build.outputs.steps.cache.cache-hit }}
          tree . -a
