name: 14 - Working with Artifacts
run-name: 14 - Working with Artifacts
on:
  workflow_dispatch:
    inputs:
      artifact-name:
        description: 'Name of the artifact to create'
        required: true
        default: 'example-artifact'
      cache-enabled:
        description: 'Enable caching for the artifact'
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Caching step
        if: ${{ inputs.cache-enabled }}
        id: cache
        uses: actions/cache@v4
        with:
          path: 14-artifacts/node_modules
          key: ${{ runner.os }}-{{ hashFiles('14-artifacts/**/package-lock.json') }}
      - name: Install Dependencies
        if: ${{ outputs.steps.cache.cache-hit != 'true' }} || ${{ !inputs.cache-enabled }}
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Create Artifact
        id: create-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}-${{ github.run_id }}
          path: 14-artifacts/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}-${{ github.run_id }}
          path: app/
      - name: install tree
        run: sudo apt-get install tree
      - name: List Artifact Contents
        run: tree .